# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attandant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('avatar', models.ImageField(upload_to='attandant/')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('room', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('attandant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Attandant')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('theme_title', models.CharField(max_length=200)),
                ('theme_description', models.TextField()),
                ('video_title', models.CharField(max_length=200)),
                ('video_subtitle', models.CharField(max_length=200)),
                ('video_description', models.TextField()),
                ('video_link', models.URLField()),
                ('conference_title', models.CharField(max_length=200)),
                ('conference_subtitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsors')),
            ],
        ),
    ]
