# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprogram',
            name='date',
            field=models.TimeField(),
        ),
    ]
