# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171225_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourprogram',
            old_name='date',
            new_name='time',
        ),
    ]
