# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171225_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='conference_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='conference_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
