# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171225_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='contact_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='contact_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
