# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171225_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gsm', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='register_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='register_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='register_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
