# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171226_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Registred', 'verbose_name_plural': 'Registred'},
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('1', 'Professor'), ('2', 'Student')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
