# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 21:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171227_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gsm',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Merci d'insérer un numéro valide", regex='^[0-9]{10}$')], verbose_name='Phone number'),
        ),
    ]
