# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171227_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Professor'), ('2', 'Student')], max_length=2, null=True),
        ),
    ]
