BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXXX
XXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXX
	XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
	XXXXXXXBBBBB BBBBBXXXX XXX XXXXBBBBBBBBXXXXXXXX

	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX

	XXXX XXXXXX XXXXXXXX XXX XXXXXXXX XXX XXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXX XXX XXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
	XXXX XXXXXX XXXX XXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXX XXXXXX XXX
	 XXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	 XXXXXX
XXXX XXXXXXXXXXXX XXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXXX
				XXXX XXXXX XXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXX
						XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
					XXXX XXXXXXXXXXXXXXXXXXX
						BB BBBBBBBB
							BBB BBBBBBB BB BBBBBBBB
								 XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							BBBBBB
						BBBBB
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
XXXX XXXXXXXXXX XXXXX  XXX
	XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXX XXXXXX XXX
			XXXX XXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
					XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
					XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXXXX
				XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
				XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
			XXXXXX
		XXXXXX
	XXXXXX
	BBBBB BBBBBBB
		
	BBBBBBBB
	XXXX XXXXXX XXXXXXX XXX
	XXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
					XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXX XXXX
					XXX XXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX
				XXXXXX
			XXXXXX
		XXXXXX
		XXXX XXXX XXX XXX
		XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

		XXXX XXXXXXX XXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
		XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
		XXXX XXXXXX XXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXX
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		BB BBBBBBBB
			XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXX
			XXXXXXXXX
		BBBBB
		BB BBBBBB
			XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXX X XXX
				XXX
			XXXXXXXXX
		BBBBB
	XXXXXXXXX
XXXXXXX
XXXXXXX